### ISSUE TITLE
arreglo en posiciones

### ISSUE THREAD

**Issue by andmarti1424** [el-ega/fpt-cli#6]
Buen día. Tuve que modificar algunas líneas puesto que la página con la fuente de datos cambió el diseño.
Esto ajusté:

![image](https://github.com/el-ega/fpt-cli/assets/9466161/e4ac2a22-1f22-4d1d-93c8-bc03d67049d2)

Disculpas que no pueda hacer un PR en estos momentos.
SAludos.

**Comment by matiasb** [comment]
Gracias! Arreglado en https://github.com/el-ega/fpt-cli/commit/67edc285e254e4f3e2142f27955438cccc451b9d, ya prepararé un release.
